/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#define Alias_Base 0x22000000U
#define Bit_Band_Mem 0x20000200U
#define Bit_Band_Base 0x20000000U

int main(void)
{

	uint8_t * Alias_Addr=(uint8_t*)(Alias_Base+(32*(Bit_Band_Mem-Bit_Band_Base))+4*7);
	*Alias_Addr&=(0);
	*Alias_Addr|=(1);

    /* Loop forever */
	for(;;);
}
