/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>
#include<main.h>


//



int main(void)
{

	/*pc_values[0] = (uint32_t *)((uint32_t)Task1_handler | 0x01);
	pc_values[1] = (uint32_t *)((uint32_t)Task2_handler | 0x01);
	pc_values[2] = (uint32_t *)((uint32_t)Task3_handler | 0x01);
	pc_values[3] = (uint32_t *)((uint32_t)Task4_handler | 0x01);*/

	Clk_Count=(HSI_CLK)/(Tick_Hz)-1;
	Clk_Init(Clk_Count);
	Init_Exceptions();
	Task_Stack_Init();
	Schedular_Stack_Init((uint32_t*)Schedular_Stack_Start);


	Change_SP_To_PSP();
	Task1_handler();






    /* Loop forever */
	for(;;);
}

uint32_t* Current_PSP(void){

 return psp_values[current_pspcount];

}
void save_psp_value(uint32_t* psp_val){
	psp_values[current_pspcount]=psp_val;
}
void update_current_pspcount(void){
	current_pspcount++;
	current_pspcount %=MAX_TASKS;

}

__attribute((naked)) void Change_SP_To_PSP(void){
	 //initialise psp
	__asm volatile("PUSH {LR}");
	__asm volatile("BL Current_PSP");
	__asm volatile ("MSR PSP,r0");
	__asm volatile ("POP {LR}");
	//changesp topsp
	__asm volatile ("MOV r0,#0x02");
	__asm volatile ("MSR CONTROL,r0");
	__asm volatile("BX LR");




}


void Clk_Init(int count){
//reload the count value into systick reload value register
*pSYST_RVR &=~(0x00FFFFFF);
*pSYST_RVR |=(count);
//configure starting 3 bits to 1 of sysctick control status register
*pSYST_CSR |=(1<<0);
*pSYST_CSR |=(1<<1);
*pSYST_CSR |=(1<<2);





}
void Task1_handler(void){
	while(1){
     printf("in task1 \n ");
	}

}
void Task2_handler(void){
	while(1){
		 printf("in task2 \n");
	}

}
void Task3_handler(void){
	while(1){
		 printf("in task3 \n");
	}

}
void Task4_handler(void){
	while(1){
		 printf("in task4 \n");
	}

}

__attribute__((naked))void Schedular_Stack_Init(uint32_t* pSchedular_Start){
	__asm volatile("MSR MSP,%0"::"r"(pSchedular_Start));
	__asm volatile("BX LR");

}


void Init_Exceptions(void){

	  uint32_t *pSHCRS = (uint32_t*) 0xE000ED24;
	   *pSHCRS |=(1<<18);
	   *pSHCRS |=(1<<17);
	   *pSHCRS |=(1<<16);


}

void Task_Stack_Init(void){
	uint32_t* psp;
for(int i=0; i<MAX_TASKS;i++){


psp=(uint32_t*)psp_values[i];

psp--;//XPSR
*psp=DUMMY_XPSR;

psp--;//PC
*psp=(uint32_t)pc_values[i];

psp--;//LR store EXC_RETURN value in it
*psp=0xFFFFFFFD;

//store r0 to 13 as 0 it will be updated later
for(int j = 0 ; j < 13 ; j++)
	{
		psp--;
	    *psp = 0;

	}
//imp:-store psp
psp_values[i]=(uint32_t*)(psp);
}
}
__attribute__((naked))void SysTick_Handler(void){
	/*Save the context of current task */


//push the fucking LR into stack
	__asm volatile("PUSH {LR}");

	//1. Get current running task's PSP value
	__asm volatile("BL Current_PSP");
	//2. Using that PSP value store SF2( R4 to R11)
	__asm volatile("STMDB R0!,{R4-R11}");
	//3. Save the current value of PSP
	__asm volatile("BL save_psp_value ");


	/*Retrieve the context of next task */

	//1. Decide next task to run
	__asm volatile("BL update_current_pspcount");
	//2. get its past PSP value
	__asm volatile("BL Current_PSP");
	//3. Using that PSP value retrieve SF2(R4 to R11)
	__asm volatile("LDMIA R0!,{R4-R11}");
	//4. update PSP and exit
	__asm volatile("MSR PSP,R0");
	__asm volatile("POP {LR}");
	__asm volatile("BX LR");



}

void HardFault_Handler (void){
printf("HardFault");
while(1);


}
void MemManage_Handler (void){
	printf("in MemManage_Handler");
	while(1);



}
void BusFault_Handler (void){
	uint32_t* pBFAR=(uint32_t*)0xE000ED38;
	printf("%ld\n",*pBFAR);
	printf("in BusFault_Handler");
	while(1);


}
 void UsageFault_Handler (void){
		printf("in UsageFault_Handler");
		while(1);


}

