/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void)
{
	//enable all exception handler
   uint32_t *pSHCRS = (uint32_t*) 0xE000ED24;
   *pSHCRS |=(1<<18);
   *pSHCRS |=(1<<17);
   *pSHCRS |=(1<<16);
   //forcefully execute undefined instruction using function pointer
   uint32_t *loc=(uint32_t*)0x20010000;
   *loc=(uint32_t)0xffffffff;
   void (*random)(void);
   random=(void*)(0x20010001);
   //in usage fault handler
   random();

   while(1);






}
void HardFault_Handler (void){
printf("HardFault");
while(1);


}
void MemManage_Handler (void){
	printf("in MemManage_Handler");
	while(1);



}
void BusFault_Handler (void){
	printf("in BusFault_Handler");
	while(1);


}
__attribute__((naked)) void UsageFault_Handler (void){
	__asm volatile("MRS r0,MSP");
	__asm volatile("B UsageFault_Handler_c ");


}

void UsageFault_Handler_c (uint32_t * pBaseStackFrame){

    uint32_t* pUsage_status =(uint32_t*)0xE000ED2A;
    printf("pUsage_status register= %lx",(*pUsage_status) & (0xffff));
    printf("in UsageFault_Handler");
    printf("pBaseStackFrame = %p\n",pBaseStackFrame);
    	printf("Value of R0 = %lx\n", pBaseStackFrame[0]);
    	printf("Value of R1 = %lx\n", pBaseStackFrame[1]);
    	printf("Value of R2 = %lx\n", pBaseStackFrame[2]);
    	printf("Value of R3 = %lx\n", pBaseStackFrame[3]);
    	printf("Value of R12 = %lx\n", pBaseStackFrame[4]);
    	printf("Value of LR = %lx\n", pBaseStackFrame[5]);
    	printf("Value of PC = %lx\n", pBaseStackFrame[6]);
    	printf("Value of XPSR = %lx\n", pBaseStackFrame[7]);

	while(1);



}

