/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include<stdint.h>
#define alias_base 0x22000200
#define bit_band_mem_addr 0x20000200
#define bit_band_addr 0x20000000
int main(void)
{

	uint8_t *ptr=(uint8_t*)0x20000200;

	*ptr=0xFF;
	//normal method
	*ptr &=!(1<<7);
	*ptr=0xFF;
	//calculating alias addr
	uint8_t* alias_addr = (uint8_t*)(alias_base+(32*(bit_band_mem_addr-bit_band_addr))+4*7 );
   *alias_addr &=0;


}
