/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include"main.h"
#include<stdio.h>
void Clk_Init(int count);
void Init_Stack(void);
uint32_t Clk_Count;
uint32_t * pSYST_CSR =(uint32_t*)0xE000E010;
uint32_t * pSYST_RVR =(uint32_t*)0xE000E014;
void Task0_Handler(void);
void Task1_Handler(void);
void Task2_Handler(void);
void Task3_Handler(void);
void Task4_Handler(void);
void Init_Exceptions(void);
void SP_TO_PSP(void);
void Schedular_Stack_Init(uint32_t* pSchedular_Start);
uint8_t Task_No=1;
typedef struct{
	uint8_t current_state;
	uint32_t block_count;
	uint32_t psp_value;
	void (*task_handler)(void);
	}tcb_t;

	tcb_t User_Tasks[MAX_TASKS];
void UPDATE_CURRENT_TASK(void);

int main(void)
{  static uint32_t COUNT=(HSI_CLOCK)/(TICK_HZ)-1;
	User_Tasks[1].psp_value=T1_STACK_START;
	User_Tasks[1].task_handler=Task1_Handler;
	User_Tasks[2].psp_value=T2_STACK_START;
	User_Tasks[2].task_handler=Task2_Handler;
	User_Tasks[3].psp_value=T3_STACK_START;
	User_Tasks[3].task_handler=Task3_Handler;
	User_Tasks[4].psp_value=T4_STACK_START;
	User_Tasks[4].task_handler=Task4_Handler;
	User_Tasks[1].current_state=TASK_READY_STATE;
	User_Tasks[2].current_state=TASK_READY_STATE;
	User_Tasks[3].current_state=TASK_READY_STATE;
	User_Tasks[4].current_state=TASK_READY_STATE;


	Init_Exceptions();
	Clk_Init(COUNT);
	Init_Stack();
	Schedular_Stack_Init((uint32_t*)SCHED_STACK_START);
	SP_TO_PSP();
	Task1_Handler();

}


uint32_t Get_Current_PSP(void){
	return User_Tasks[Task_No].psp_value;


}

void Clk_Init(int count){
//reload the count value into systick reload value register
*pSYST_RVR &=~(0x00FFFFFF);
*pSYST_RVR |=(count);
//configure starting 3 bits to 1 of sysctick control status register

*pSYST_CSR |=(1<<1);
*pSYST_CSR |=(1<<2);
*pSYST_CSR |=(1<<0);

}

void Init_Stack(void){
//initialise sf1
	uint32_t* pPSP;
	for(int i=1;i<MAX_TASKS;i++){
		pPSP=(uint32_t*)User_Tasks[i].psp_value;

	    pPSP--;
	    *pPSP=(uint32_t)DUMMY_XPSR;

	    pPSP--;
	   	*pPSP=(uint32_t)User_Tasks[i].task_handler;

	    pPSP--;
	   	 *pPSP=0xFFFFFFFD;

	   	for(int j = 0 ; j < 13 ; j++)
	   		{
	   	 pPSP--;
	   		    *pPSP = 0;

	   		}

	   	User_Tasks[i].psp_value=(uint32_t)pPSP;

       }




}
__attribute__((naked))void Schedular_Stack_Init(uint32_t* pSchedular_Start){
	__asm volatile("MSR MSP,%0"::"r"(pSchedular_Start));
	__asm volatile("BX LR");

}
void Init_Exceptions(void){
	uint32_t *pSHCSR = (uint32_t*)0xE000ED24;

	*pSHCSR |= ( 1 << 16); //mem manage
	*pSHCSR |= ( 1 << 17); //bus fault
	*pSHCSR |= ( 1 << 18); //usage fault


}

__attribute__((naked))void SP_TO_PSP(void){
	__asm volatile("PUSH {LR}");
	__asm volatile("BL Get_Current_PSP");
	__asm volatile("POP {LR}");
	__asm volatile("MSR PSP, R0");

	__asm volatile ("MOV R0,#0X02");
	__asm volatile ("MSR CONTROL,R0");
	__asm volatile ("BX LR");

	}
void UPDATE_CURRENT_TASK(void){
	Task_No++;
	Task_No=Task_No%5;
}
void Save_Current_PSP (uint32_t psp_val){
	User_Tasks[Task_No].psp_value=psp_val;
}


void SysTick_Handler(void){

	//store the context of older task
	__asm volatile("PUSH {LR}");
	__asm volatile("BL Get_Current_PSP");
	__asm volatile("STMDB R0!,{R4-R11}");
	__asm volatile("BL Save_Current_PSP");

	__asm volatile("BL UPDATE_CURRENT_TASK");
	__asm volatile("LDMIA R0!,{R4-R11}");
	__asm volatile("POP {LR}");
	__asm volatile("BX LR");








}


void Task0_Handler(void){
	while(1);
}
void Task1_Handler(void){

	while(1){
		printf("Task1_Handler");
	}
}

void Task2_Handler(void){

	while(1){
		printf("Task2_Handler");
	}
}
void Task3_Handler(void){

	while(1){
		printf("Task3_Handler");
	}
}
void Task4_Handler(void){

	while(1){
		printf("Task4_Handler");
	}
}
void HardFault_Handler(void)
{
	printf("Exception : Hardfault\n");
	while(1);
}


void MemManage_Handler(void)
{
	printf("Exception : MemManage\n");
	while(1);
}

void BusFault_Handler(void)
{
	printf("Exception : BusFault\n");
	while(1);
}

