/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
__attribute__ ((naked)) void Change_SP_To_PSP(void){

	__asm volatile(".equ Stack_Start,0x20000000");
		__asm volatile(".equ Stack_Size,(1024*128)");
		__asm volatile(".equ MSP_Size,Stack_Start-Stack_Size/2");
		__asm volatile(".equ PSP_Start,MSP_Size");
		__asm volatile("LDR r0,=PSP_Start");
		__asm volatile("MSR PSP, r0");
		__asm volatile("LDR r0,=#0x02");
		__asm volatile("MSR CONTROL,r0");
		__asm volatile ("BX LR");


}
int main(void)
{

	Change_SP_To_PSP();

    /* Loop forever */
	for(;;);
}
