/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#define NVIC_ISER_BASE  0xE000E100U
#define NVIC_ISPR_BASE  0XE000E200U
#define NVIC_ICPR_BASE  0XE000E280U
#define NVIC_IPR_BASE   0xE000E400U
void Enable_Interrupt(uint8_t irq_no , uint8_t priority_value){
	uint8_t offset=irq_no/32;
	uint32_t* pISER=(uint32_t*)(NVIC_ISER_BASE+(offset)*4);
	offset=irq_no%32;
	*pISER|=(1<<offset);
	offset=irq_no/4;
	uint32_t* pIPR=(uint32_t*)(NVIC_IPR_BASE+4*(offset));
	offset=irq_no%4;
	*pIPR|=(priority_value<<8*offset);
	//bas pending register ko set karo thats it !!


}

int main(void)
{


    /* Loop forever */
	for(;;);
}
