/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{	uint32_t * pSHCSR = (uint32_t*) 0xE000ED24;
*pSHCSR |=(1<<18);
*pSHCSR |=(1<<17);
*pSHCSR |=(1<<16);

	void (*fp)(void);
	fp=(void*)0x400FFFFF;
	fp();


    /* Loop forever */
	for(;;);
}
void HardFault_Handler(void){

	printf("hard fault /n");
		while(1);
}
void MemManage_Handler(void){
	printf("memmanage fault /n");
		while(1);

}
void BusFault_Handler(void){
	printf("bus fault /n");
		while(1);

}
void UsageFault_Handler(void){

	printf("usage fault /n");
	while(1);


}


