/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#define base_addr_ISER (uint32_t*)0xE000E100
#define base_addr_IPR 0xE000E400
#define base_addr_ISPR 0xE000E200
#define IRQ_NO_TIMER2 28
#define IRQ_NO_I2C1 31
#define PRIO_TIMER2 0x80
#define PRIO_I2C1 0x70

  void config_priority_for_interrupt(uint8_t prio_value,uint8_t irq_no){

	  uint32_t * IPR_addr=(uint32_t*)(base_addr_IPR +(irq_no/4));
	  uint8_t SHIFT_VALUE =(irq_no%4)*8;
	  *IPR_addr &=~(0xff << SHIFT_VALUE);
	  *IPR_addr |=(prio_value<<SHIFT_VALUE);




  }

int main(void)
{//1. Lets configure the priority for the peripherals
    config_priority_for_interrupt(PRIO_TIMER2,IRQ_NO_TIMER2);
    config_priority_for_interrupt(PRIO_I2C1,IRQ_NO_I2C1);

    //2. Set the interrupt pending bit in the NVIC PR
    uint32_t * ISPR_TIMER_addr= (uint32_t*)(base_addr_ISPR+(IRQ_NO_TIMER2/32));
    *ISPR_TIMER_addr |=(1<<(IRQ_NO_TIMER2%32))   ;
    //3. Enable the IRQs in NVIC ISER
    *base_addr_ISER |=(1<<IRQ_NO_TIMER2);
    *base_addr_ISER |=(1<<IRQ_NO_I2C1);

}
void I2C1_EV_IRQHandler(void){
	printf("in I2C IRQ handler");


}
void TIM2_IRQHandler(void){
	printf("in timer IRQ handler");
	uint32_t * ISPR_I2C_addr= (uint32_t*)(base_addr_ISPR+(IRQ_NO_I2C1/32));
		    *ISPR_I2C_addr |=(1<<(IRQ_NO_I2C1%32));
		    while(1);
}
