/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>
uint8_t svc_number=0;

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	printf("calling svc exception now\n");
    __asm volatile("SVC #0x8");
    printf("svc number is %d\n",svc_number);

	for(;;);
}

__attribute((naked)) void SVC_Handler(void){

	__asm volatile("MRS r0,MSP");
	__asm volatile("ADD r0,r0,#24");
	__asm volatile("LDR r1,[r0]");
	__asm volatile ("SUB r1,r1,#02");
	__asm volatile("LDRB r2,[r1] ");
	__asm volatile ("MOV %0,r2":"=r"(svc_number));
	__asm volatile ("BX LR");

}
